### ISSUE TITLE
BrokenPipeError：[Broken pipe]

### ISSUE THREAD

**Issue by Jessiswong** [jeffchy/RE2RNN#4]
when I reproduced your code, there was always a problem that I couldn't solve. I asked you for help:
When I run the code command python create_automata.py --dataset ATIS --automata_name all --reversed 0
the error will be：
BrokenPipeError：[Broken pipe]
![捕获](https://user-images.githubusercontent.com/62866048/111032332-88cf7e00-8403-11eb-8218-f7850ce4dcca.JPG)

**Comment by jeffchy** [comment]
It might be caused by the drawGraph() function, which uses the "dot" command.
Two ways to solve it. 1. Install the dot command (actually it is pre-installed in many Linux distributes) 2. drawGraph will generate a .png of the automata, if you do not need that, you can just don't use the drawGraph() function (e.g. comment it out).
